spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

  mvc:
    path match:
      matching-strategy: ant_path_matcher
    format:
      date-time: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jpa:
    hibernate:
      ddl-auto: create

  kafka:
    producer:
      value-serializer: com.server.event.util.EventDTOSerializer
    consumer:
      value-deserializer: com.server.event.util.ResponseEventDTODeserializer

    bootstrap-servers: localhost:9092


kafka:
  input_topic: input_topic
  finished_topic: finished_topic
  failed_topic: failed_topic

server:
  port: 8099
